-- EN ÇOK TOPLAM TUTARA SAHÝP ALIÞVERÝÞÝ YAPAN ÝSTANBUL'DAKÝ KADINLAR ,

SELECT DISTINCT USERS.ID,USERNAME_,NAMESURNAME,GENDER,TOTALPRICE,COUNTRY,CITY 
FROM USERS
		INNER JOIN ORDERS ON ORDERS.USERID=USERS.ID
		INNER JOIN ORDERDETAILS ON ORDERDETAILS.ORDERID=ORDERS.ID
		INNER JOIN ADDRESS ON ADDRESS.ID=ORDERS.ADDRESSID
		INNER JOIN COUNTRIES ON COUNTRIES.ID=ADDRESS.COUNTRYID
		INNER JOIN CITIES ON CITIES.ID=ADDRESS.CITYID

WHERE USERS.GENDER='K' AND CITIES.CITY='ÝSTANBUL'
ORDER BY TOTALPRICE DESC

--TOPLAM CÝRO ÜZERÝNDE SATIÞ YAPAN ÞEHÝRLER

SELECT AVG(DISTINCT TOTALPRICE) FROM ORDERS
  --434.705

SELECT CITIES.CITY,
COUNT(ORDERS.ID) AS TOPLAM_SÝPARÝÞ_SAYISI,
SUM(ORDERS.TOTALPRICE) TOPLAM_CÝRO,
SUM(ORDERS.TOTALPRICE)/COUNT(ORDERS.ID) SÝPARÝÞ_BAÞINA_CÝRO

FROM ORDERS
		INNER JOIN USERS ON ORDERS.USERID=USERS.ID
		INNER JOIN ORDERDETAILS ON ORDERDETAILS.ORDERID=ORDERS.ID
		INNER JOIN ADDRESS ON ADDRESS.ID=ORDERS.ADDRESSID
		INNER JOIN COUNTRIES ON COUNTRIES.ID=ADDRESS.COUNTRYID
		INNER JOIN CITIES ON CITIES.ID=ADDRESS.CITYID

GROUP BY CITIES.CITY

--EN ÇOK SÝPARÝÞ VEREN ÞEHÝR

SELECT CITIES.CITY,COUNT(ORDERS.ID)

FROM ORDERS
		INNER JOIN USERS ON ORDERS.USERID=USERS.ID
		INNER JOIN ORDERDETAILS ON ORDERDETAILS.ORDERID=ORDERS.ID
		INNER JOIN ADDRESS ON ADDRESS.ID=ORDERS.ADDRESSID
		INNER JOIN COUNTRIES ON COUNTRIES.ID=ADDRESS.COUNTRYID
		INNER JOIN CITIES ON CITIES.ID=ADDRESS.CITYID

GROUP BY CITIES.CITY
ORDER BY COUNT(ORDERS.ID) DESC


