-- EN ÇOK TOPLAM TUTARA SAHÝP ALIÞVERÝÞÝ YAPAN ÝSTANBUL'DAKÝ KADINLAR ,

SELECT DISTINCT USERS.ID,USERNAME_,NAMESURNAME,GENDER,TOTALPRICE,COUNTRY,CITY 
FROM USERS
INNER JOIN ORDERS 
ON ORDERS.USERID=USERS.ID

INNER JOIN ORDERDETAILS
ON ORDERDETAILS.ORDERID=ORDERS.ID

INNER JOIN ADDRESS 
ON ADDRESS.ID=ORDERS.ADDRESSID

INNER JOIN COUNTRIES 
ON COUNTRIES.ID=ADDRESS.COUNTRYID

INNER JOIN CITIES
ON CITIES.ID=ADDRESS.CITYID

WHERE USERS.GENDER='K' AND CITIES.CITY='ÝSTANBUL'
ORDER BY TOTALPRICE DESC

